config/routes.rb
Rails.application.routes.draw do
  get 'favorite_foods/create'
  get 'favorite_foods/destroy'
  # トップページ（8/11追加）
  root "foods#search"

  # Foodページ（8/11追加）
  resources :foods, only: %i[index show] do
    collection do
      get :search
    end
    # お気に入り食品機能（8/23追加）
    member do
      post 'favorite'
      delete 'unfavorite'
    end
    # レビューページ（8/21追加）
    resources :reviews, only: %i[new create edit update destroy]
  end

  # ユーザーページ（8/12追加）
  resources :users, only: %i[new create show]

  # ログインページ（8/12追加）
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  get 'about', to: 'pages#about'
end

app/views/shared/_before_login_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">

    <div class="container-fluid">
      <!-- ハンバーガーメニュー -->
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- ナビゲーション -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <%= link_to I18n.t("header.home"), root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to I18n.t("header.about"), about_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to I18n.t("header.before_login"), login_path, class: "nav-link" %>
          </li>
        </ul>
        <!-- 検索フォーム -->
        <%= form_with(scope: :search, url: foods_path, method: :get, local: true) do |f| %>
          <div class="d-flex">
            <%= f.text_field :keyword, value: @search_params[:keyword], class:"form-control me-sm-2", placeholder: I18n.t("placeholder.keyword") %>
            <%= f.submit I18n.t("buttons.search"), class:"btn btn-secondary my-2 my-sm-0" %>
          </div>
        <% end %>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="flash-message <%= message_type %>">
    <%= message %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="bg-primary text-white text-center mt-auto py-3">
    <div class="container-fluid">
        <p class="mb-0"><%= I18n.t("footer.copyright") %></p>
    </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">

    <div class="container-fluid">
      <!-- ハンバーガーメニュー -->
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- ナビゲーション -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <%= link_to I18n.t("header.home"), root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to I18n.t("header.about"), about_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to I18n.t("header.mypage", name: current_user.name), user_path(current_user), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to I18n.t("header.logout"), logout_path, class: "nav-link", data: { turbo_method: :delete } %>
          </li>
        </ul>
        <!-- 検索フォーム -->
        <%= form_with(scope: :search, url: foods_path, method: :get, local: true) do |f| %>
          <div class="d-flex">
            <%= f.text_field :keyword, value: @search_params[:keyword], class:"form-control me-sm-2", placeholder: I18n.t("placeholder.keyword") %>
            <%= f.submit I18n.t("buttons.search"), class:"btn btn-secondary my-2 my-sm-0" %>
          </div>
        <% end %>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_search_before_login_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg" data-bs-theme="dark">

    <div class="container-fluid">
      <!-- ハンバーガーメニュー -->
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- ナビゲーション -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <%= link_to I18n.t("header.home"), root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to I18n.t("header.about"), about_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to I18n.t("header.before_login"), login_path, class: "nav-link" %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_search_footer.html.erb
<footer class="text-white text-center mt-auto py-3">
    <div class="container">
        <p class="mb-0"><%= I18n.t("footer.copyright") %></p>
    </div>
</footer>

app/views/shared/_search_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg" data-bs-theme="dark">

    <div class="container-fluid">
      <!-- ハンバーガーメニュー -->
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- ナビゲーション -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <%= link_to I18n.t("header.home"), root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to I18n.t("header.about"), about_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to I18n.t("header.mypage", name: current_user.name), user_path(current_user), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to I18n.t("header.logout"), logout_path, class: "nav-link", data: { turbo_method: :delete } %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>