config/routes.rb
Rails.application.routes.draw do
  get 'favorite_foods/create'
  get 'favorite_foods/destroy'
  # トップページ（8/11追加）
  root "foods#search"

  # Foodページ（8/11追加）
  resources :foods, only: %i[index show] do
    collection do
      get :search
    end
    # お気に入り食品機能（8/23追加）
    member do
      post 'favorite'
      delete 'unfavorite'
    end
    # レビューページ（8/21追加）
    resources :reviews, only: %i[new create edit update destroy]
  end

  # ユーザーページ（8/12追加）
  resources :users, only: %i[new create show]

  # ログインページ（8/12追加）
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  get 'about', to: 'pages#about'
end

app/models/food.rb
class Food < ApplicationRecord
  # 外部キー制約（8/11追加）
  belongs_to :food_category
  belongs_to :food_country
  has_many :reviews, dependent: :destroy

  # お気に入り食品機能（8/23追加）
  has_many :favorite_foods
  has_many :favorited_by, through: :favorite_foods, source: :user

  # FoodモデルでCarrierWaveを使用するように設定（8/12追加）
  mount_uploader :food_image, FoodImageUploader

  # 検索メソッド（8/11追加）
  scope :search, -> (search_params) do
    # search_paramsが空の場合以降の処理を行わない。
    return if search_params.blank?

    # パラメータを指定して検索する
    food_country_id_is(search_params[:food_country_id])
      .food_category_id_is(search_params[:food_category_id])
      .price_from(search_params[:price_from])
      .price_to(search_params[:price_to])
      .keyword_like(search_params[:keyword])
  end

  scope :food_country_id_is, -> (food_country_id) { where(food_country_id: food_country_id) if food_country_id.present? }
  scope :food_category_id_is, -> (food_category_id) { where(food_category_id: food_category_id) if food_category_id.present? }
  scope :price_from, -> (from) { where('? <= price', from) if from.present? }
  scope :price_to, -> (to) {
    if to.present?
      where('price <= ? AND price > 0', to) # priceが0より大きく、指定したto以下
    else
      where('price >= 0') # price_to が指定されていない場合の条件
    end
  }
  scope :keyword_like, -> (keyword) {
    where('name LIKE :keyword OR
           title LIKE :keyword OR
           body LIKE :keyword', keyword: "%#{keyword}%") if keyword.present?
  }
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  skip_before_action :require_login, only: %i[index search show]
  before_action :set_food, only: [:favorite, :unfavorite]

  # トップページ（8/11追加）
  def search
    @header_type = "search_header"
    @footer_type = "search_footer"
    @body_class = "search-background"
    # 初期化処理
    @search_params = {}
  end

  # 食品検索結果一覧ページ（8/11追加）
  def index
    @body_class = "background"

    # 検索条件をセッションに保存（8/25追加）
    if params[:search]
      session[:food_search] = food_search_params.to_h
    end

    @search_params = session[:food_search] || {}
    @foods = Food.search(@search_params).includes(:food_category, :food_country)

    # ページネーション（8/11追加）
    sort_order = case params[:sort]
    when 'old'
      'created_at ASC'
    when 'hot'
      'spice_level DESC'
    when 'mild'
      'spice_level ASC'
    else
      'created_at DESC'
    end

    # 現在のソートオプションを保存（8/19追加）
    @current_sort = params[:sort] || 'new'

    @total_count = @foods.count
    @foods = @foods.order(sort_order).page(params[:page]).per(10)
  end

  # 食品詳細表示ページ
  def show
    @body_class = "background"

    @food = Food.find(params[:id])
    @reviews = @food.reviews # ここで関連するレビューを取得（8/13追加）

    # ページネーション（8/11追加）
    sort_order = case params[:sort]
    when 'old'
      'created_at ASC'
    else
      'created_at DESC'
    end

    @current_sort = params[:sort] || 'new'
    @reviews = @reviews.order(sort_order).page(params[:page]).per(3)
  end

  # お気に入り食品機能（8/23追加）
  def favorite
    current_user.favorite(@food)
    redirect_to @food, notice: I18n.t("food.favorite.notice")
  end

  def unfavorite
    current_user.unfavorite(@food)
    redirect_to @food, notice: I18n.t("food.unfavorite.notice")
  end

  private

  def food_search_params
    params.fetch(:search, {}).permit(:food_country_id,
                                 :food_category_id,
                                 :price_from,
                                 :price_to,
                                 :keyword)
  end

  # お気に入り食品機能（8/23追加）
  def set_food
    @food = Food.find(params[:id])
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/index.html.erb
<% content_for(:title, I18n.t("food.index.title")) %>

<% breadcrumb :food_index, @foods %>

<div class="container my-5">

  <!-- タイトル -->
  <div class="title">
    <h1><%= I18n.t("food.index.title") %></h1>
  </div>
  <div class="subtitle">
    <% if @total_count != 0 %>
      <% count_html = content_tag(:span, @total_count, class: "fw-bold text-primary") %>
      <p><%= I18n.t("food.index.subtitle", count: count_html).html_safe %></p>
    <% else %>
      <p><%= I18n.t("food.index.no_food") %></p>
    <% end %>
  </div>

  <!-- 検索結果一覧 -->
  <% if @foods.present? %>
    <div class="index-form"> 

      <!-- ページネーション -->
      <div class="text-end">
        <%= link_to I18n.t("views.pagination.new"), foods_path(sort: 'new'), class: "pe-2 text-decoration-none #{'text-decoration-underline' if @current_sort == 'new'}", style: "color: #fda085;" %>
        <%= link_to I18n.t("views.pagination.old"), foods_path(sort: 'old'), class: "pe-2 text-decoration-none #{'text-decoration-underline' if @current_sort == 'old'}", style: "color: #fda085;" %>
        <%= link_to I18n.t("views.pagination.hot"), foods_path(sort: 'hot'), class: "pe-2 text-decoration-none #{'text-decoration-underline' if @current_sort == 'hot'}", style: "color: #fda085;" %>
        <%= link_to I18n.t("views.pagination.mild"), foods_path(sort: 'mild'), class: "pe-1 text-decoration-none #{'text-decoration-underline' if @current_sort == 'mild'}", style: "color: #fda085;" %>
      </div>

      <!-- 検索結果カード -->
      <div class="row">
        <% @foods.each do |food| %>
          <div class="col-12 col-md-6 mt-4 d-flex">
            <%= link_to food_path(food), class: "card index-card border-primary d-flex flex-row text-decoration-none" do %>
              <!-- 食品写真 -->
              <div class="d-flex align-items-center">
                <%= image_tag(food.food_image.present? ? food.food_image.url : "image_ramen.png", class: "img-fluid index-food-image") %>
              </div>
              <div class="d-flex flex-column mt-4 me-2">
                <!-- 食品名 -->
                <h5 class="card-title fw-bold"><%= food.name %></h5>
                <!-- 食品タグ -->
                <h6 class="fw-bold"><span class="badge rounded-pill bg-danger"><%= food.food_category.name %></span></h6>
                <!-- 辛さレベル -->
                <span class="card-text fw-bold">
                  <%=  I18n.t("activerecord.attributes.food.spice_level") %>
                  <!-- 赤 -->
                  <% food.spice_level.times do %>
                    <i class="bi bi-fire text-danger"></i>
                  <% end %>
                  <!-- グレー -->        
                  <% (5 - food.spice_level).times do %>
                    <i class="bi bi-fire text-secondary"></i>
                  <% end %>
                </span>
                <!-- 希望小売価格 -->
                <span class="card-text fw-bold">
                  <%=  I18n.t("activerecord.attributes.food.price") %>
                  <% if food.price != 0 %>
                    <%= number_to_currency(food.price, unit: I18n.t("food.index.en"), format: "%n %u", precision: 0) %><%= I18n.t("food.index.in_price") %>
                  <% else %>
                    <%= I18n.t("food.index.open_price") %>
                  <% end %>
                </span>
              </div>
            <% end %>
          </div>
        <% end %>

        <!-- ページネーション -->
        <div class="mt-3 custom-pagination">
          <%= paginate @foods, theme: 'bootstrap-5' %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/foods/search.html.erb
<% content_for(:title) %>

<% breadcrumb :root %>

<div class="container my-5">

  <!-- タイトル -->
  <div class="search-title">
    <h1 class="mt-5"><%= I18n.t("food.search.title") %></h1>
    <p><%= I18n.t("food.search.subtitle") %></p>
  </div>

  <!-- 検索フォーム -->
  <%= form_with(scope: :search, url: foods_path, method: :get, local: true, class: "search-form") do |f| %>
    <div class="row">
      <div class="col-12 col-md-6">
        <!-- 国から探す（セレクトボックス） -->
        <%= f.label :food_country_id, "#{I18n.t("activerecord.attributes.food.food_country_id")}#{I18n.t("food.search.from")}", class: "form-label fw-bold text-primary" %>
        <%= f.collection_select(:food_country_id, FoodCountry.all, :id, :name, { selected: @search_params[:food_country_id], include_blank: true }, { class: "form-select search-border border-primary" }) %>
      </div>
      <div class="col-12 col-md-6">
        <!-- 値段から探す（範囲指定） -->
        <%= f.label :price, "#{I18n.t("activerecord.attributes.food.price")}#{I18n.t("food.search.from")}", class: "form-label fw-bold text-primary" %>
        <div class="d-flex align-items-center">
          <%= f.select :price_from, options_for_select([0, 100, 200, 300, 400, 500, 600, 700, 800, 900, 1000].map { |price| ["#{price}円", price] }, @search_params[:price_from]), { include_blank: true }, class:"form-control search-border border-primary" %>
          <span class="mx-2"> ~ </span>
          <%= f.select :price_to, options_for_select([0, 100, 200, 300, 400, 500, 600, 700, 800, 900, 1000].map { |price| ["#{price}円", price] }, @search_params[:price_to]), { include_blank: true }, class:"form-control search-border border-primary" %>
        </div>
      </div>
    </div>
    <div class="row mt-3">
      <div class="col-12 col-md-6">
        <!-- カテゴリから探す（セレクトボックス） -->
        <%= f.label :food_category_id, "#{I18n.t("activerecord.attributes.food.food_category_id")}#{I18n.t("food.search.from")}", class: "form-label fw-bold text-primary" %>
        <%= f.collection_select(:food_category_id, FoodCategory.all, :id, :name, { selected: @search_params[:food_category_id], include_blank: true }, { class: "form-select search-border border-primary" }) %>
      </div>
      <div class="col-12 col-md-6">
        <!-- キーワードから探す（テキストフィールド） -->
        <%= f.label :keyword, "#{I18n.t("food.search.keyword")}#{I18n.t("food.search.from")}", class: "form-label fw-bold text-primary" %>
        <%= f.text_field :keyword, value: @search_params[:keyword], class:"form-control search-border border-primary" %>
      </div>
    </div>
    <div class="row mt-3">
      <div class="col-12">
        <%= f.submit I18n.t("buttons.search"), class:"btn search-btn" %>
      </div>
    </div>
  <% end %>
</div>

app/views/foods/show.html.erb
<% content_for(:title, @food.name) %>

<% breadcrumb :food_show, @food %>

<div class="container my-5">

  <!-- タイトル -->
  <div class="title">
    <h1><%= I18n.t("food.show.title") %></h1>
  </div>

  <!-- 食品詳細 -->
  <div class="show-food-form">
    <div class="row">

      <!-- 食品画像 -->
      <div class="col-12 col-md-6 mt-4 d-flex">
        <div class="d-flex flex-column align-items-center">
          <%= image_tag(@food.food_image.present? ? @food.food_image.url : "image_ramen.png", class: "img-fluid show-food-image") %>
          <!-- お気に入り食品機能（8/23追加） -->
          <% if current_user && current_user.favorite?(@food) %>
            <%= button_to unfavorite_food_path(@food), method: :delete, remote: true, class: "btn unfavorite-btn" do %>
              <i class="bi bi-bookmark-heart-fill"></i><%= I18n.t("food.show.unfavorite") %>
            <% end %>
          <% else %>
            <%= button_to favorite_food_path(@food), method: :post, remote: true, class: "btn favorite-btn" do %>
              <i class="bi bi-bookmark-heart"></i><%= I18n.t("food.show.favorite") %>
            <% end %>
          <% end %>
          <span class="mt-3"><%= I18n.t("food.show.favorite_login") %></span>
        </div>
      </div>
      <div class="col-12 col-md-6 mt-4">
        <!-- 食品名 -->
        <h2 class="fw-bold mt-5"><%= @food.name %></h2>
        <!-- 食品タグ -->
        <h5 class="fw-bold mt-3"><span class="badge rounded-pill bg-danger"><%= @food.food_category.name %></span></h5>
        <!-- 辛さレベル -->
        <h6 class="fw-bold mt-4">
          <%=  I18n.t("activerecord.attributes.review.spice_level") %>
          <!-- 赤 -->
          <% @food.spice_level.times do %>
            <i class="bi bi-fire text-danger"></i>
          <% end %>
          <!-- グレー -->
          <% (5 - @food.spice_level).times do %>
            <i class="bi bi-fire text-secondary"></i>
          <% end %>
        </h6>
        <!-- 希望小売価格 -->
        <h6 class="fw-bold">
          <%=  I18n.t("activerecord.attributes.food.price") %>
          <% if @food.price != 0 %>
            <%= number_to_currency(@food.price, unit: I18n.t("food.index.en"), format: "%n %u", precision: 0) %><%= I18n.t("food.index.in_price") %>
          <% else %>
            <%= I18n.t("food.index.open_price") %>
          <% end %>
        </h6>
        <hr class="border-custom">
        <!-- タイトル -->
        <h6 class="fw-bold mt-3"><%= @food.title %></h6>
        <!-- 説明 -->
        <p class="mt-3"><%= @food.body %></p>
        <!-- 引用元 -->
        <h6 class="mt-4">
          <span class="fw-bold"><%= I18n.t("activerecord.attributes.food.from") %></span>&nbsp;<%= @food.from %>
        </h6>  
      </div>
    </div>
  </div>

  <!-- タイトル -->
  <div id="show-review-title" class="title mt-5">
    <h1><%= I18n.t("food.show.review", food_name: @food.name) %></h1>
  </div>
  <div class="subtitle mt-5">
    <% unless @reviews.present? %>
      <p class="mt-5"><%= I18n.t("food.show.no_review") %></p>
    <% end %>
    <!-- 投稿ボタン -->
    <div class="d-flex justify-content-between align-items-center mt-3">
      <%= link_to I18n.t("buttons.post"), new_food_review_path(@food), class:"btn post-btn" %>
    </div>
    <span class="mt-3"><%= I18n.t("food.show.review_login") %></span>
  </div>

  <!-- レビュー一覧 -->
  <% if @reviews.present? %>
    <div class="show-review-form">
      <!-- ページネーション -->
      <div class="text-end">
        <%= link_to I18n.t("views.pagination.new"), food_path(@food, sort: 'new', anchor: 'show-review-title'), class: "pe-2 text-decoration-none #{'text-decoration-underline' if @current_sort == 'new'}", style: "color: #fda085;" %>
        <%= link_to I18n.t("views.pagination.old"), food_path(@food, sort: 'old', anchor: 'show-review-title'), class: "text-decoration-none #{'text-decoration-underline' if @current_sort == 'old'}", style: "color: #fda085;" %>
      </div>

      <!-- レビュー一覧 -->
      <div class="row">
        <% @reviews.each do |review| %>
          <div class="col-12 mb-4">
            <!-- ユーザー名 -->
            <h5 class="fw-bold mt-2 mx-2 text-primary">
              <%= link_to review.user.name, user_path(review.user) %>
            </h5>
            <div class="show-review-flex">
              <!-- 辛さレベル -->
              <p class="fw-bold mt-0 mx-2 mb-0 p-0" style="display: inline-block;">
                <%=  I18n.t("activerecord.attributes.review.spice_level") %>
                <% review.spice_level.times do %>
                    <i class="bi bi-fire text-danger"></i>
                <% end %>
                <% (5 - review.spice_level).times do %>
                    <i class="bi bi-fire text-secondary"></i>
                <% end %>
              </p>
              <div class="show-review-icon mb-0 me-4 p-0">
                <% if current_user == review.user %>
                  <div class="btn-group me-2" role="group">
                    <!-- 編集タグ -->
                    <%= link_to edit_food_review_path(@food, review), class:"btn btn-outline-warning" do %>
                      <i class="bi bi-pencil-fill"></i>
                    <% end %>
                    <!-- 削除タグ -->
                    <%= link_to food_review_path(@food, review), class:"btn btn-outline-warning", data: { turbo_method: :delete, turbo_confirm: I18n.t("buttons.confirm") } do %>
                      <i class="bi bi-trash"></i></i>
                    <% end %>
                  </div>                 
                <% else %>
                  <!-- いいねタグ -->
                  <!--
                  <%= link_to "#", class:"btn btn-outline-warning" do %>
                    <i class="bi bi-heart-fill"></i>
                  <% end %>
                  -->
                <% end %>
              </div>
            </div>
            <hr class="border border-primary border-2 my-1">
            <!-- タイトル -->
            <p class="fw-bold my-0 mx-2 p-0">
              <%= review.title %>
            </p>
            <!-- 評価 -->
            <p class="my-0 mx-2 p-0">
              <%= review.rating %>
            </p>
          </div>
        <% end %>
      </div>

      <!-- ページネーション -->
      <div class="mt-3 custom-pagination">
        <%= paginate @reviews, theme: "bootstrap-5", params: { anchor: "show-review-title" } %>
      </div>
    </div>
  <% end %>
</div>